server_path: /home/jack/NEW-BACKEND/server/server.py

# Speech-to-Text Configuration
stt:
  enabled: true                    # Enable/disable STT functionality
  api_key_env: "DEEPGRAM_API_KEY"  # Environment variable containing Deepgram API key
  model: "nova-2"                  # Deepgram model to use
  language: "en-US"                # Language for transcription
  utterance_end_ms: 1000           # Milliseconds to wait before considering utterance ended
  keepalive_interval: 3            # Seconds between keepalive messages during streaming responses
