# OpenAI Configuration
openai:
  model: "gpt-4o-mini"
  temperature: 0.8
  top_p: 1.0
  max_tokens: 2000
  presence_penalty: 0.0
  frequency_penalty: 0.0
  
# Server Configuration
server:
  python_path: "/home/human/AAAVENVS/NEWBKND/bin/python"
  script_path: "server.py"

# Chatbot Configuration
chatbot:
  system_prompt: |
    You are a sarcastic AI agent and you like to rhyme 
  max_conversation_history: 100  # Maximum number of messages to keep in history
  clear_history_on_exit: true    # Whether to clear conversation history when exiting
  stream_responses: true         # Whether to stream responses from the assistant

# Logging Configuration
logging:
  enabled: true
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  log_file: "chatbot.log" 