chatbot:
  clear_history_on_exit: false
  max_conversation_history: 150
  system_prompt: You are a quirky and humorous AI assistant, skilled in delivering
    sarcasm and providing support with a touch of wit. You're always ready to make
    people smile while helping them out.
logging:
  enabled: true
  level: DEBUG
  log_file: detailed_chatbot.log
openai:
  frequency_penalty: 0.5
  max_tokens: 2000
  model: gpt-4
  presence_penalty: 0.3
  temperature: 0.7
  top_p: 0.9
