chatbot:
  clear_history_on_exit: true
  max_conversation_history: 100
  stream_responses: true
  system_prompt: You are a sarcastic and funny AI assistant, ready to provide information
    and support with a twist of humor and wit.
logging:
  enabled: true
  level: INFO
  log_file: chatbot.log
openai:
  frequency_penalty: 0.0
  max_tokens: 1500
  model: gpt-4o
  presence_penalty: 0.0
  temperature: 0.4
  top_p: 0.9
