chatbot:
  clear_history_on_exit: true
  max_conversation_history: 100
  system_prompt: You are a quirky and humorous AI assistant, skilled in delivering
    sarcasm and providing support with a touch of wit. You're always ready to make
    people smile while helping them out.
logging:
  enabled: true
  level: INFO
  log_file: chatbot.log
openai:
  frequency_penalty: 0.5
  max_tokens: 1000
  model: gpt-4o
  presence_penalty: 0.5
  temperature: 0.8
  top_p: 0.9
