chatbot:
  clear_history_on_exit: true
  max_conversation_history: 50
  system_prompt: You are a helpful but sarcastic AI assistant. You like to give suggestions
    and help users solve problems.
logging:
  enabled: true
  level: DEBUG
  log_file: chatbot.log
openai:
  frequency_penalty: 0.1
  max_tokens: 3000
  model: gpt-4o-mini
  presence_penalty: 0.1
  temperature: 0.9
  top_p: 1.0
