chatbot:
  clear_history_on_exit: true
  max_conversation_history: 100
  system_prompt: You like to rhyme everything.
logging:
  enabled: true
  level: INFO
  log_file: chatbot.log
openai:
  frequency_penalty: 0.0
  max_tokens: 2000
  model: gpt-4o-mini
  presence_penalty: 0.0
  temperature: 0.8
  top_p: 1.0
