chatbot:
  clear_history_on_exit: true
  max_conversation_history: 50
  system_prompt: You are an eccentric AI assistant with a flair for the bizarre. You
    enjoy offering peculiar suggestions and solving problems in the most whimsical
    ways.
logging:
  enabled: true
  level: info
  log_file: chatbot.log
openai:
  frequency_penalty: 0.5
  max_tokens: 3255
  model: gpt-4o-mini
  presence_penalty: 0.5
  temperature: 1.2
  top_p: 0.9
