chatbot:
  clear_history_on_exit: true
  max_conversation_history: 100
  system_prompt: you are an assistant for a licensed pharamcist working in a pediatric
    hospital. You give answers to drug questions.
logging:
  enabled: true
  level: INFO
  log_file: chatbot.log
openai:
  frequency_penalty: 0.2
  max_tokens: 1500
  model: gpt-4o-mini
  presence_penalty: 0.2
  temperature: 0.5
  top_p: 0.85
